// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpHmbJXhXxMOZev7YQXgRpG6-4X4ngiAM',
    appId: '1:185880170660:web:74f488d3ad682b50dcd631',
    messagingSenderId: '185880170660',
    projectId: 'chefup-e9c65',
    authDomain: 'chefup-e9c65.firebaseapp.com',
    storageBucket: 'chefup-e9c65.firebasestorage.app',
    measurementId: 'G-PP0SHDDJ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm6N66iZev5PbChk3SHaOgpPEu81tnSlk',
    appId: '1:185880170660:android:2a5a986f8cd3eb5bdcd631',
    messagingSenderId: '185880170660',
    projectId: 'chefup-e9c65',
    storageBucket: 'chefup-e9c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXsTxVn3Qg_kOxZO8qHAF1i0ppsKsibu0',
    appId: '1:185880170660:ios:46e0f734b297bc87dcd631',
    messagingSenderId: '185880170660',
    projectId: 'chefup-e9c65',
    storageBucket: 'chefup-e9c65.firebasestorage.app',
    iosBundleId: 'com.example.chefup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXsTxVn3Qg_kOxZO8qHAF1i0ppsKsibu0',
    appId: '1:185880170660:ios:46e0f734b297bc87dcd631',
    messagingSenderId: '185880170660',
    projectId: 'chefup-e9c65',
    storageBucket: 'chefup-e9c65.firebasestorage.app',
    iosBundleId: 'com.example.chefup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpHmbJXhXxMOZev7YQXgRpG6-4X4ngiAM',
    appId: '1:185880170660:web:3c35315627056a05dcd631',
    messagingSenderId: '185880170660',
    projectId: 'chefup-e9c65',
    authDomain: 'chefup-e9c65.firebaseapp.com',
    storageBucket: 'chefup-e9c65.firebasestorage.app',
    measurementId: 'G-35R1T4E9KN',
  );
}
